/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GenderService } from "../gender.service";
import { GenderCreateInput } from "./GenderCreateInput";
import { Gender } from "./Gender";
import { GenderFindManyArgs } from "./GenderFindManyArgs";
import { GenderWhereUniqueInput } from "./GenderWhereUniqueInput";
import { GenderUpdateInput } from "./GenderUpdateInput";
import { StudentFindManyArgs } from "../../student/base/StudentFindManyArgs";
import { Student } from "../../student/base/Student";
import { StudentWhereUniqueInput } from "../../student/base/StudentWhereUniqueInput";

export class GenderControllerBase {
  constructor(protected readonly service: GenderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Gender })
  async createGender(@common.Body() data: GenderCreateInput): Promise<Gender> {
    return await this.service.createGender({
      data: data,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Gender] })
  @ApiNestedQuery(GenderFindManyArgs)
  async genders(@common.Req() request: Request): Promise<Gender[]> {
    const args = plainToClass(GenderFindManyArgs, request.query);
    return this.service.genders({
      ...args,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Gender })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async gender(
    @common.Param() params: GenderWhereUniqueInput
  ): Promise<Gender | null> {
    const result = await this.service.gender({
      where: params,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Gender })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGender(
    @common.Param() params: GenderWhereUniqueInput,
    @common.Body() data: GenderUpdateInput
  ): Promise<Gender | null> {
    try {
      return await this.service.updateGender({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Gender })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGender(
    @common.Param() params: GenderWhereUniqueInput
  ): Promise<Gender | null> {
    try {
      return await this.service.deleteGender({
        where: params,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/students")
  @ApiNestedQuery(StudentFindManyArgs)
  async findStudents(
    @common.Req() request: Request,
    @common.Param() params: GenderWhereUniqueInput
  ): Promise<Student[]> {
    const query = plainToClass(StudentFindManyArgs, request.query);
    const results = await this.service.findStudents(params.id, {
      ...query,
      select: {
        age: true,
        createdAt: true,

        gender: {
          select: {
            id: true,
          },
        },

        grade: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,

        section: {
          select: {
            id: true,
          },
        },

        subjects: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/students")
  async connectStudents(
    @common.Param() params: GenderWhereUniqueInput,
    @common.Body() body: StudentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      students: {
        connect: body,
      },
    };
    await this.service.updateGender({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/students")
  async updateStudents(
    @common.Param() params: GenderWhereUniqueInput,
    @common.Body() body: StudentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      students: {
        set: body,
      },
    };
    await this.service.updateGender({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/students")
  async disconnectStudents(
    @common.Param() params: GenderWhereUniqueInput,
    @common.Body() body: StudentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      students: {
        disconnect: body,
      },
    };
    await this.service.updateGender({
      where: params,
      data,
      select: { id: true },
    });
  }
}
