/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { GenderWhereUniqueInput } from "../../gender/base/GenderWhereUniqueInput";
import { GradeWhereUniqueInput } from "../../grade/base/GradeWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { SectionWhereUniqueInput } from "../../section/base/SectionWhereUniqueInput";
import { JsonFilter } from "../../util/JsonFilter";

@InputType()
class StudentWhereInput {
  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  age?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => GenderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GenderWhereUniqueInput)
  @IsOptional()
  @Field(() => GenderWhereUniqueInput, {
    nullable: true,
  })
  gender?: GenderWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => GradeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GradeWhereUniqueInput)
  @IsOptional()
  @Field(() => GradeWhereUniqueInput, {
    nullable: true,
  })
  grade?: GradeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => SectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SectionWhereUniqueInput)
  @IsOptional()
  @Field(() => SectionWhereUniqueInput, {
    nullable: true,
  })
  section?: SectionWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  subjects?: JsonFilter;
}

export { StudentWhereInput as StudentWhereInput };
