/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { GenderWhereUniqueInput } from "../../gender/base/GenderWhereUniqueInput";
import { Type } from "class-transformer";
import { GradeWhereUniqueInput } from "../../grade/base/GradeWhereUniqueInput";
import { SectionWhereUniqueInput } from "../../section/base/SectionWhereUniqueInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class StudentCreateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  age?: number | null;

  @ApiProperty({
    required: false,
    type: () => GenderWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GenderWhereUniqueInput)
  @IsOptional()
  @Field(() => GenderWhereUniqueInput, {
    nullable: true,
  })
  gender?: GenderWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => GradeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GradeWhereUniqueInput)
  @IsOptional()
  @Field(() => GradeWhereUniqueInput, {
    nullable: true,
  })
  grade?: GradeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => SectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => SectionWhereUniqueInput)
  @IsOptional()
  @Field(() => SectionWhereUniqueInput, {
    nullable: true,
  })
  section?: SectionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  subjects?: InputJsonValue;
}

export { StudentCreateInput as StudentCreateInput };
